In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("golf_df.csv")
df.head(3)

Outlook Temperature Humidity  Windy Play
0     sunny         hot     high  False   no
1     sunny         hot     high   True   no
2  overcast         hot     high  False  yes

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le=LabelEncoder()
Outlook_le=le.fit_transform(df.Outlook)
Temperature_le=le.fit_transform(df.Temperature)
Humidity_le=le.fit_transform(df.Humidity)
Windy_le=le.fit_transform(df.Windy)
Play_le=le.fit_transform(df.Play)



In [5]:
df["Outlook_le"]=Outlook_le
df["Temperature_l1"]=Temperature_le
df["Humidity_le"]=Humidity_le
df["Windy_le"]=Windy_le
df["Play_le"]=Play_le
df.head(3)

Outlook Temperature Humidity  Windy Play  Outlook_le  Temperature_l1  \
0     sunny         hot     high  False   no           2               1   
1     sunny         hot     high   True   no           2               1   
2  overcast         hot     high  False  yes           0               1   

   Humidity_le  Windy_le  Play_le  
0            0         0        0  
1            0         1        0  
2            0         0        1

In [6]:
df=df.drop(["Outlook","Temperature","Humidity","Windy","Play"],axis=1)


In [7]:
df.head(3)

Outlook_le  Temperature_l1  Humidity_le  Windy_le  Play_le
0           2               1            0         0        0
1           2               1            0         1        0
2           0               1            0         0        1

In [8]:
x=df.iloc[:,0:4]
x.head(3)

Outlook_le  Temperature_l1  Humidity_le  Windy_le
0           2               1            0         0
1           2               1            0         1
2           0               1            0         0

In [9]:
y=df.iloc[:,4:]
y.head(3)

Play_le
0        0
1        0
2        1

In [10]:
y.shape

(14, 1)

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [12]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

c:\softwares\python_virtual\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


GaussianNB()

In [13]:
y_predict=model.predict(x_test)

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(y_test,y_predict,normalize=True)

1.0

In [16]:
model.predict_proba([[2,1,0,0]])

array([[0.70635895, 0.29364105]])

In [17]:
model.predict([[2,1,0,0]])

array([0])

In [18]:
model.predict_proba([[2,2,1,0]])

array([[0.1523891, 0.8476109]])

In [19]:
model.predict([[2,2,1,0]])

array([1])